{
  "formatVersion": "1.1",
  "component": {
    "group": "com.michael-bull.kotlin-retry",
    "module": "kotlin-retry",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "25d3v5m62jecpmrrsl5lxvzpnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-retry-1.0.8.jar",
          "url": "kotlin-retry-1.0.8.jar",
          "size": 55178,
          "sha512": "4377e5908d94d47cbe0ec2e6dee2963607be390affbe882738189cf85aa2c094b841cdc486e27940b44cd51ce85915f71bbeb541533f151d8216eae5c68d8727",
          "sha256": "cc8e406f0572cb93a845547ab3bb4690ab4ee8fef3594ee2833ab2fa39a39e29",
          "sha1": "2cc5cfd0ee1695a40b81279fddcec8d88bdd53aa",
          "md5": "2887c8b87aeb93a97fc2411f73e41e83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-retry-1.0.8.jar",
          "url": "kotlin-retry-1.0.8.jar",
          "size": 55178,
          "sha512": "4377e5908d94d47cbe0ec2e6dee2963607be390affbe882738189cf85aa2c094b841cdc486e27940b44cd51ce85915f71bbeb541533f151d8216eae5c68d8727",
          "sha256": "cc8e406f0572cb93a845547ab3bb4690ab4ee8fef3594ee2833ab2fa39a39e29",
          "sha1": "2cc5cfd0ee1695a40b81279fddcec8d88bdd53aa",
          "md5": "2887c8b87aeb93a97fc2411f73e41e83"
        }
      ]
    }
  ]
}
